#========================kubernetesノードの共通プロビジョニング============================
TargetCon1:
  ConnParm:
  - hostname: 192.168.112.20,192.168.112.21,192.168.112.22
  - port: 22
  - userid: ubuntu
  - passwd: _${UBUNTUPASS}
  # ope内で改行を入れたい場合は改行箇所を\nとすること
  Operation:
  # kubernetes共通プロビジョニングスクリプトの転送，プロビジョニングの実施
  #- ope: scp@put@_${SOURCEWORKDIR}\kubernetes\kubecommonprov.sh@/home/ubuntu
  - ope: scp@put@_${SOURCEWORKDIR}/kubernetes/kubecommonprov.sh@/home/ubuntu 
  - ope: sudo bash /home/ubuntu/kubecommonprov.sh _${PROXYVAR} 2>&1