#========================kubernetesマスターノードのプロビジョニング============================
TargetCon1:
  ConnParm:
  - hostname: 192.168.112.21,192.168.112.22
  - port: 22
  - userid: ubuntu
  - passwd: _${UBUNTUPASS}
  # ope内で改行を入れたい場合は改行箇所を\nとすること
  Operation:
  # kubernetes共通プロビジョニングスクリプトの転送，プロビジョニングの実施
  #- ope: scp@put@_${SOURCEWORKDIR}\kubernetes\kubeadm_join_cmd.sh@/home/ubuntu
  - ope: scp@put@_${SOURCEWORKDIR}/kubernetes/kubeadm_join_cmd.sh@/home/ubuntu 
  #- ope: scp@put@_${SOURCEWORKDIR}\kubernetes\kubeworkerprov.sh@/home/ubuntu
  - ope: scp@put@_${SOURCEWORKDIR}/kubernetes/kubeworkerprov.sh@/home/ubuntu 
  - ope: sudo bash /home/ubuntu/kubeworkerprov.sh _${PROXYVAR} _${MASTERNODEIP} 2>&1