#========================kubernetesノードの共通プロビジョニング============================
TargetCon1:
  ConnParm:
  - hostname: 192.168.112.20,192.168.112.21,192.168.112.22
  - port: 22
  - userid: ubuntu
  - passwd: _${UBUNTUPASS}
  # ope内で改行を入れたい場合は改行箇所を\nとすること
  Operation:
  # NodeExporterインストール
  #- ope: scp@put@_${SOURCEWORKDIR}\kubernetes\nodeexporterInstall.sh@/home/ubuntu
  - ope: scp@put@_${SOURCEWORKDIR}/kubernetes/nodeexporterInstall.sh@/home/ubuntu 
  - ope: sudo bash /home/ubuntu/nodeexporterInstall.sh _${PROXYVAR} 2>&1
  # master-nodeのcorednsに以下設定をいれる→やっぱりいらない。けどナレッジのためになんか残す
  # sudo kubectl edit configmap coredns -n kube-system
  
  #  Corefile: |
  #  .:53 {
  #      errors
  #      health
  #      ここから
  #      hosts {
  #         192.168.112.20 simkube-master
  #         192.168.112.21 simkube-node1
  #         192.168.112.22 simkube-node2
  #         192.168.112.23 simkube-node3
  #         fallthrough
  #      }
  #      ここまで
  #      kubernetes cluster.local in-addr.arpa ip6.arpa {
  #         pods insecure
  #         ここも↓ 
  #         upstream 192.168.112.2
  #         fallthrough in-addr.arpa ip6.arpa
  #      }
  #      prometheus :9153
  #      #forward . /etc/resolv.conf
  #      ここも↓
  #      forward . 192.168.112.2
  #      cache 30
  #      loop
  #      reload
  #      loadbalance
  #  }