TargetCon1:
  ConnParm:
  - hostname: 192.168.11.13
  - port: 22
  - userid: sim
  - passwd: _${SIMPASSWD}
  # ope内で改行を入れたい場合は改行箇所を\nとすること
  Operation:
  ################ kubernetes MasterNode削除 ####################
  - ope: "aws ec2 terminate-instances --instance-ids `cat _${WORKDIR}/instance-id-_${MASTERHOST}.txt`"
  # MasterNode削除確認
  - ope: "#!/bin/bash\n
          while :\n
          do\n
             ping _${MASTERNODEIP} -c 1 >> /dev/null\n
             if [ $? == 1 ]; then\n
                echo \"_${MASTERNODEIP} Del ok\"\n
                break\n
             fi\n
             sleep 3\n
          done"
  ################ kubernetes Node1削除 ####################
  - ope: "aws ec2 terminate-instances --instance-ids `cat _${WORKDIR}/instance-id-_${NODE1HOST}.txt`"
  # Node1削除確認
  - ope: "#!/bin/bash\n
          while :\n
          do\n
             ping _${NODE1IP} -c 1 >> /dev/null\n
             if [ $? == 1 ]; then\n
                echo \"_${NODE1IP} Del ok\"\n
                break\n
             fi\n
             sleep 3\n
          done"
  ################ kubernetes Node2削除 ####################
  - ope: "aws ec2 terminate-instances --instance-ids `cat _${WORKDIR}/instance-id-_${NODE2HOST}.txt`"
  # Node2削除確認
  - ope: "#!/bin/bash\n
          while :\n
          do\n
             ping _${NODE2IP} -c 1 >> /dev/null\n
             if [ $? == 1 ]; then\n
                echo \"_${NODE2IP} Del ok\"\n
                break\n
             fi\n
             sleep 3\n
          done"