TargetCon1:
  ConnParm:
  - hostname: 192.168.11.13
  - port: 22
  - userid: sim
  - passwd: _${SIMPASSWD}
  # ope内で改行を入れたい場合は改行箇所を\nとすること
  Operation:
  ################ ロードバランサー削除 ####################
  - ope: "aws elbv2 delete-load-balancer --load-balancer-arn `cat _${WORKDIR}/simkube-lb-arn.txt`"
  ################ ターゲットグループ削除 ####################
  - ope: "aws elbv2 delete-target-group --target-group-arn `cat _${WORKDIR}/simkube-prometheus-target-arn.txt`"
  - ope: "aws elbv2 delete-target-group --target-group-arn `cat _${WORKDIR}/simkube-grafana-target-arn.txt`"