TargetCon1:
  ConnParm:
  - hostname: 192.168.11.13
  - port: 22
  - userid: sim
  - passwd: _${SIMPASSWD}
  # ope内で改行を入れたい場合は改行箇所を\nとすること
  Operation:
  # 事後作業（作業ディレクトリの削除）
  - ope: "rm -rf _${WORKDIR} 2>&1"